/* Bayi Gelişim Analizi — Performans > Gelişim */
var DEV_BAYI=null,DEV_PERIOD=null,DEV_MODE='ytd';
var DEV_MONTHS=['Ocak','Şubat','Mart','Nisan','Mayıs','Haziran','Temmuz','Ağustos','Eylül','Ekim','Kasım','Aralık'];
var DEV_SHORT=['Oca','Şub','Mar','Nis','May','Haz','Tem','Ağu','Eyl','Eki','Kas','Ara'];
var DEV_PRODUCTS=[{key:'mobil',label:'MOBİL',icon:'▯',color:'#1473E6'},{key:'dsl',label:'DSL',icon:'◉',color:'#7037D3'},{key:'tv',label:'IPTV',icon:'▣',color:'#F06A27'},{key:'cihaz',label:'AKILLI CİHAZ',icon:'▱',color:'#12A887'}];
function devPeriods(){return Object.keys(HIST2_DATA||{}).filter(function(p){return!!HIST2_DATA[p];}).sort();}
function devDealerList(){var p=devPeriods();if(!p.length)return[];return(HIST2_DATA[p[p.length-1]].dealers||[]).slice().sort(function(a,b){return(a.bayiAdi||'').localeCompare(b.bayiAdi||'','tr');});}
function devDealer(p,k){var d=HIST2_DATA[p];return d?(d.dealers||[]).find(function(x){return String(x.bayiKodu)===String(k);})||null:null;}
function devAddMonths(p,n){var y=+p.slice(0,4),m=+p.slice(5)-1+n;y+=Math.floor(m/12);m=((m%12)+12)%12;return y+'-'+String(m+1).padStart(2,'0');}
function devAgg(d){var n=0;DEV_PRODUCTS.forEach(function(p){n+=d&&d[p.key]?(+d[p.key].adet||0):0;});return n;}
function devYtd(k,p){var y=p.slice(0,4),mm=+p.slice(5),o={total:0,prods:{},months:0};DEV_PRODUCTS.forEach(function(x){o.prods[x.key]=0;});devPeriods().forEach(function(q){if(q.slice(0,4)!==y||+q.slice(5)>mm)return;var d=devDealer(q,k);if(!d)return;o.months++;DEV_PRODUCTS.forEach(function(x){var n=d[x.key]?(+d[x.key].adet||0):0;o.prods[x.key]+=n;o.total+=n;});});return o;}
function devPct(c,p){return p?(c-p)/p*100:null;}function devFmt(n){return Math.round(n||0).toLocaleString('tr-TR');}
function devDelta(n){return'<span class="dev-delta '+(n>=0?'up':'down')+'">'+(n>=0?'+':'')+devFmt(n)+' adet</span>';}
function devPctHtml(n){if(n===null||!isFinite(n))return'<span class="dev-pct flat">—</span>';return'<span class="dev-pct '+(n>=0?'up':'down')+'">'+(n>=0?'+':'')+'%'+Math.abs(n).toFixed(1).replace('.',',')+'</span>';}
function devSelectBayi(v){DEV_BAYI=v;renderDevelopment();}function devSelectPeriod(v){DEV_PERIOD=v;renderDevelopment();}function devSetMode(v){DEV_MODE=v;renderDevelopment();}
function devSeries(k,key,p,count){var a=[];for(var i=count-1;i>=0;i--){var d=devDealer(devAddMonths(p,-i),k);a.push(d&&d[key]?+d[key].adet||0:0);}return a;}
function devSpark(a,c){if(!a.length)return'';var mn=Math.min.apply(null,a),mx=Math.max.apply(null,a),s=mx-mn||1,pts=a.map(function(v,i){return(i*52/Math.max(a.length-1,1)).toFixed(1)+','+(16-(v-mn)/s*12).toFixed(1);}).join(' ');return'<svg class="dev-spark" viewBox="0 0 54 18"><polyline points="'+pts+'" fill="none" stroke="'+c+'" stroke-width="1.5"/></svg>';}
function devFilters(ds,ps){var b=ds.map(function(d){return'<option value="'+d.bayiKodu+'" '+(String(d.bayiKodu)===String(DEV_BAYI)?'selected':'')+'>'+d.bayiAdi+' · '+d.bayiKodu+'</option>';}).join(''),p=ps.slice().reverse().map(function(x){return'<option value="'+x+'" '+(x===DEV_PERIOD?'selected':'')+'>'+x.slice(0,4)+' '+DEV_MONTHS[+x.slice(5)-1]+'</option>';}).join('');return'<div class="dev-filter-card"><label><span>Bayi Seçimi</span><select onchange="devSelectBayi(this.value)">'+b+'</select></label><div class="dev-mode"><span>Kıyas Modu</span><div><button class="'+(DEV_MODE==='ytd'?'on':'')+'" onclick="devSetMode(\'ytd\')">YTD</button><button class="'+(DEV_MODE==='yoy'?'on':'')+'" onclick="devSetMode(\'yoy\')">YoY</button><button class="'+(DEV_MODE==='trend'?'on':'')+'" onclick="devSetMode(\'trend\')">Aylık Trend</button></div></div><label><span>Dönem</span><select onchange="devSelectPeriod(this.value)">'+p+'</select></label></div>';}
function devKpis(c,o){var h='<div class="dev-kpis"><div class="dev-kpi dev-kpi-total"><div class="dev-kpi-label">TOPLAM ÜRETİM (YTD)</div><div class="dev-kpi-num">'+devFmt(c.total)+'</div><small>adet</small><div class="dev-total-bars"><i></i><i></i><i></i></div><div class="dev-kpi-foot">'+devDelta(c.total-o.total)+devPctHtml(devPct(c.total,o.total))+'</div></div>';DEV_PRODUCTS.forEach(function(p){var n=c.prods[p.key],old=o.prods[p.key];h+='<div class="dev-kpi" style="--pc:'+p.color+'"><div class="dev-kpi-label"><b>'+p.icon+'</b>'+p.label+'</div><div class="dev-kpi-num">'+devFmt(n)+'</div><small>adet</small>'+devSpark(devSeries(DEV_BAYI,p.key,DEV_PERIOD,8),p.color)+'<div class="dev-kpi-foot">'+devDelta(n-old)+devPctHtml(devPct(n,old))+'</div></div>';});return h+'</div>';}
function devChart(k,p){var a=[];for(var i=11;i>=0;i--){var q=devAddMonths(p,-i),d=devDealer(q,k),o=devDealer(devAddMonths(q,-12),k);a.push({p:q,c:d?devAgg(d):null,o:o?devAgg(o):null});}var vals=[];a.forEach(function(x){if(x.c!==null)vals.push(x.c);if(x.o!==null)vals.push(x.o);});var max=Math.max.apply(null,vals.concat([1]));function xy(v,i){return{x:32+i*27.2,y:135-v/max*102};}function line(key){var z=[];a.forEach(function(x,i){if(x[key]!==null){var q=xy(x[key],i);z.push(q.x.toFixed(1)+','+q.y.toFixed(1));}});return z.join(' ');}var labels=a.map(function(x,i){return'<text x="'+(32+i*27.2).toFixed(1)+'" y="154" text-anchor="middle">'+DEV_SHORT[+x.p.slice(5)-1]+'</text>';}).join(''),dots=a.map(function(x,i){if(x.c===null)return'';var q=xy(x.c,i);return'<circle cx="'+q.x+'" cy="'+q.y+'" r="2.7"/><text class="val" x="'+q.x+'" y="'+(q.y-7)+'" text-anchor="middle">'+x.c+'</text>';}).join(''),ct=a.reduce(function(s,x){return s+(x.c||0);},0),ot=a.reduce(function(s,x){return s+(x.o||0);},0),last=a[a.length-1],diff=(last.c||0)-(last.o||0);return'<section class="dev-panel"><div class="dev-panel-title">AYLIK ADETSEL GELİŞİM <small>(Son 12 Ay)</small></div><div class="dev-legend"><span><i class="old"></i>Önceki yıl</span><span><i></i>Seçili dönem</span></div><svg class="dev-chart" viewBox="0 0 340 162" preserveAspectRatio="none"><g class="grid"><line x1="28" y1="33" x2="332" y2="33"/><line x1="28" y1="84" x2="332" y2="84"/><line x1="28" y1="135" x2="332" y2="135"/></g><polyline class="oldline" points="'+line('o')+'"/><polyline class="newline" points="'+line('c')+'"/><g class="dots">'+dots+'</g><g>'+labels+'</g></svg><div class="dev-chart-summary"><div><small>SON 12 AY TOPLAM</small><b>'+devFmt(ct)+' adet</b><span>Önceki: '+devFmt(ot)+'</span>'+devDelta(ct-ot)+devPctHtml(devPct(ct,ot))+'</div><div><small>SON AY YOY</small><b>'+devFmt(last.c)+' adet</b><span>'+devFmt(last.o)+' adet</span>'+devDelta(diff)+devPctHtml(devPct(last.c||0,last.o||0))+'</div></div></section>';}
function devYoY(k,p){var y=p.slice(0,4),max=+p.slice(5),r='',tc=0,to=0;for(var m=1;m<=max;m++){var q=y+'-'+String(m).padStart(2,'0'),d=devDealer(q,k),o=devDealer(devAddMonths(q,-12),k);if(!d&&!o)continue;var c=d?devAgg(d):0,old=o?devAgg(o):0,z=c-old;tc+=c;to+=old;r+='<tr><td>'+DEV_MONTHS[m-1]+'</td><td>'+devFmt(old)+'</td><td>'+devFmt(c)+'</td><td class="'+(z>=0?'up':'down')+'">'+(z>=0?'+':'')+devFmt(z)+'</td><td>'+devPctHtml(devPct(c,old))+'</td></tr>';}return'<section class="dev-panel dev-yoy"><div class="dev-panel-title">AY AY KARŞILAŞTIRMA (YoY)</div><div class="dev-table-scroll"><table><thead><tr><th>Ay</th><th>'+(+y-1)+'</th><th>'+y+'</th><th>Fark</th><th>Fark (%)</th></tr></thead><tbody>'+r+'</tbody><tfoot><tr><td>TOPLAM</td><td>'+devFmt(to)+'</td><td>'+devFmt(tc)+'</td><td>'+(tc-to>=0?'+':'')+devFmt(tc-to)+'</td><td>'+devPctHtml(devPct(tc,to))+'</td></tr></tfoot></table></div></section>';}
function devAnalysis(c,o){var a=DEV_PRODUCTS.map(function(p){return{p:p,c:c.prods[p.key],d:c.prods[p.key]-o.prods[p.key],pct:devPct(c.prods[p.key],o.prods[p.key])};}),pos=a.filter(function(x){return x.d>=0;}).sort(function(x,y){return y.d-x.d;}),neg=a.filter(function(x){return x.d<0;}).sort(function(x,y){return x.d-y.d;}),vol=a.slice().sort(function(x,y){return y.c-x.c;})[0];function list(x){return x.slice(0,3).map(function(v,i){return'<div class="dev-rank"><b>'+(i+1)+'</b><span style="color:'+v.p.color+'">'+v.p.icon+'</span><strong>'+v.p.label+'</strong>'+devDelta(v.d)+devPctHtml(v.pct)+'</div>';}).join('')||'<div class="dev-none">Gerileyen ürün bulunmuyor.</div>';}return'<section class="dev-panel"><div class="dev-panel-title">ÜRÜN BAZLI GELİŞİM ANALİZİ (YTD)</div><div class="dev-analysis-grid"><div class="dev-analysis good"><small>EN ÇOK GELİŞEN</small>'+list(pos)+'</div><div class="dev-analysis bad"><small>EN ÇOK GERİLEYEN</small>'+list(neg)+'</div><div class="dev-analysis volume"><small>EN BÜYÜK HACİM</small><div class="dev-donut" style="--share:'+Math.round(vol.c/c.total*100)+'%"></div><b>'+vol.p.label+'</b><strong>'+devFmt(vol.c)+' adet</strong><span>Toplamın %'+(vol.c/c.total*100).toFixed(1).replace('.',',')+'’i</span></div></div></section>';}
function devNarrative(info,c,o){var pct=devPct(c.total,o.total)||0,a=DEV_PRODUCTS.map(function(p){return{p:p,d:c.prods[p.key]-o.prods[p.key],c:c.prods[p.key]};}),best=a.slice().sort(function(x,y){return y.d-x.d;})[0],worst=a.slice().sort(function(x,y){return x.d-y.d;})[0],vol=a.slice().sort(function(x,y){return y.c-x.c;})[0];var manager='<p><b>'+info.bayiAdi+'</b>, geçen yılın aynı dönemine göre toplamda <em class="'+(pct>=0?'up':'down')+'">%'+Math.abs(pct).toFixed(1).replace('.',',')+' '+(pct>=0?'büyüme':'daralma')+'</em> göstermiştir.</p>'+a.map(function(x){return'<p><i class="'+(x.d>=0?'up':'down')+'">'+(x.d>=0?'↑':'↓')+'</i> '+x.p.label+' tarafında '+(x.d>=0?'artış':'gerileme')+' bulunmaktadır.</p>';}).join('');var ins=[['▥','YTD büyüme ivmesi '+(pct>=0?'pozitif':'negatif'),'Toplamda '+devFmt(c.total-o.total)+' adet değişim.'],['♙','En güçlü gelişim',best.p.label+' '+devFmt(best.d)+' adet.'],['▣',worst.d<0?worst.p.label+' dikkat gerektiriyor':'Gerileyen ürün yok','YTD eğilimi izlenmeli.'],['▱',vol.p.label+' lider ürün','Toplam hacmin %'+(vol.c/c.total*100).toFixed(1).replace('.',',')+'’i.']];return'<div class="dev-bottom"><section class="dev-panel"><div class="dev-panel-title">YÖNETİCİ ÖZETİ</div><div class="dev-manager">'+manager+'</div></section><section class="dev-panel"><div class="dev-panel-title">KISA İÇGÖRÜLER</div><div class="dev-insights">'+ins.map(function(x,i){return'<div><b class="c'+i+'">'+x[0]+'</b><p><strong>'+x[1]+'</strong><span>'+x[2]+'</span></p></div>';}).join('')+'</div></section></div>';}
async function renderDevelopment(){var cards=document.getElementById('cards');if(!cards)return;cards.className='cards single';cards.style.maxWidth='100%';if(!HIST2_LOADED){cards.innerHTML='<div class="dev-loading">Geçmiş veriler yükleniyor…</div>';await loadAllHistory();return renderDevelopment();}var ps=devPeriods(),ds=devDealerList();if(!ps.length||!ds.length){cards.innerHTML='<div class="dev-loading">Gelişim analizi için geçmiş veri bulunamadı.</div>';return;}if(!DEV_PERIOD||ps.indexOf(DEV_PERIOD)<0)DEV_PERIOD=ps[ps.length-1];if(!DEV_BAYI||!ds.some(function(d){return String(d.bayiKodu)===String(DEV_BAYI);}))DEV_BAYI=String(ds[0].bayiKodu);var info=devDealer(DEV_PERIOD,DEV_BAYI)||ds[0],c=devYtd(DEV_BAYI,DEV_PERIOD),o=devYtd(DEV_BAYI,devAddMonths(DEV_PERIOD,-12));cards.innerHTML='<div class="dev-page" id="development-card"><div class="dev-head"><div><h2>Bayi Gelişim Analizi</h2><p>Geçmişe göre adetsel gelişiminizi analiz edin</p></div><button onclick="downloadCardPNG()">⌯ Paylaş</button></div>'+devFilters(ds,ps)+devKpis(c,o)+'<div class="dev-main-grid">'+devChart(DEV_BAYI,DEV_PERIOD)+devYoY(DEV_BAYI,DEV_PERIOD)+'</div>'+devAnalysis(c,o)+devNarrative(info,c,o)+'</div>';}
