/* YD Performans · Prim & Kazanç — Eylül 2026 */
var earningsState={investor:'all',protection:false,tab:'overview'};
function _eData(){return window.YD_PRIM_DATA||null}
function _eFmtTL(n){return new Intl.NumberFormat('tr-TR',{style:'currency',currency:'TRY',maximumFractionDigits:0}).format(Number(n||0))}
function _eFmt(n,d){return Number(n||0).toLocaleString('tr-TR',{minimumFractionDigits:d||0,maximumFractionDigits:d||0})}
function _eInvestor(){var d=_eData();if(!d||earningsState.investor==='all')return null;return d.investors.find(function(x){return x.id===earningsState.investor})||null}
function _eCurrentYppBarem(points){var out=null;(_eData().yppBarems||[]).forEach(function(b){if(points>=b.points)out=b});return out}
function _eNextYppBarem(points){return (_eData().yppBarems||[]).find(function(b){return b.points>points})||{points:40500,amount:1665000}}
function _eNextBpp(hgo){var rows=_eData().bppBarems||[];for(var i=0;i<rows.length;i++){if(hgo<rows[i].min)return rows[i]}return null}
function _eCatStatus(v){if(v<70)return ['Katkı yok','bad'];if(v>=100)return [v>130?'%130 tavan':'Hedef üstü','good'];return ['Aktif','mid']}
function _eSharePotential(inv){if(!inv||!inv.yppRate)return 0;var next=_eNextYppBarem(inv.points);var nextPay=next.amount*(inv.yppRate/100);return Math.max(0,nextPay-inv.ypp)}
function _eBppPotential(inv){if(!inv)return 0;var next=_eNextBpp(inv.hgo);if(!next)return 0;return Math.max(0,inv.base*(next.rate/100)-inv.bpp)}
function earningsSelectInvestor(v){earningsState.investor=v;renderEarningsPage()}
function earningsToggleProtection(){earningsState.protection=!earningsState.protection;renderEarningsPage()}
function earningsTab(v){earningsState.tab=v;renderEarningsPage()}
function _eKpi(label,value,sub,cls){return '<div class="earn-card earn-kpi '+(cls||'')+'"><div class="lbl">'+label+'</div><div class="val">'+value+'</div><div class="sub '+(sub&&sub.cls||'')+'">'+(sub&&sub.text||'')+'</div></div>'}
function _eOverview(d,inv){
  var p=d.portfolio,bpp=inv?inv.bpp:(earningsState.protection?p.protectedBpp:p.bpp),ypp=inv?inv.ypp:p.ypp,points=inv?inv.points:p.points,hgo=inv?inv.hgo:p.hgo,total=bpp+ypp;
  var kpis='<div class="earn-kpis">'+
    _eKpi('Hesaplanan Prim',_eFmtTL(total),{text:earningsState.protection&&!inv?'Yeni şube koruması dahil':'26 Eylül itibarıyla tahmini'},'primary')+
    _eKpi('YPP Kazancı',_eFmtTL(ypp),{text:inv&&inv.yppRate?'Paylaşım %'+inv.yppRate:'Yatırımcı bazlı hesap'})+
    _eKpi('BPP Kazancı',_eFmtTL(bpp),{text:inv?'Paylaşım %'+inv.bppRate:(earningsState.protection?'Koruma açık':'Standart hesap')})+
    _eKpi('YPP Puanı',_eFmt(points),{text:inv?'Yatırımcı puanı':'Portföy toplam puanı',cls:'muted'})+
    _eKpi('Ağırlıklı HGO','%'+_eFmt(hgo,2),{text:inv?'Yatırımcı HGO':'Portföy yönetim görünümü',cls:'muted'})+
    _eKpi('Veri Durumu','BPP / YPP',{text:'Eylül kural seti aktif',cls:'muted'})+'</div>';
  var baremTitle,baremNote,left,right,width,gain,gainText;
  if(inv){var cur=_eCurrentYppBarem(inv.points),next=_eNextYppBarem(inv.points),rem=Math.max(0,next.points-inv.points),start=cur?cur.points:0;baremTitle=_eFmt(inv.points)+' puan';baremNote=_eFmt(next.points)+' YPP baremine '+_eFmt(rem)+' puan kaldı';left=_eFmt(start);right=_eFmt(next.points);width=Math.max(4,Math.min(100,start===next.points?100:((inv.points-start)/(next.points-start))*100));gain=_eSharePotential(inv);gainText=gain?'Sonraki YPP bareminin ek etkisi':(inv.yppRate?'Sonraki barem hesaplanıyor':'Önce HGO %80 paylaşım eşiği gerekli')}
  else{baremTitle='Yatırımcı seçerek fırsatı gör';baremNote='Sonraki YPP/BPP baremi ve TL etkisi yatırımcı bazında hesaplanır.';left='3.500';right='38.500+';width=68;gain=earningsState.protection?160000:0;gainText=earningsState.protection?'Yeni şube korumasının BPP etkisi':'Koruma senaryosu kapalı'}
  var barem='<div class="earn-card earn-section"><div class="earn-head"><div><div class="earn-title">Sonraki Barem</div><div class="earn-sub">Puan ve kazanç fırsatı</div></div><span class="earn-pill">'+(inv?inv.name:'Portföy')+'</span></div><div class="earn-barem"><div><div class="earn-barem-big">'+baremTitle+'</div><div class="earn-barem-note">'+baremNote+'</div><div class="earn-track"><div class="earn-fill" style="width:'+width+'%"></div></div><div class="earn-track-labels"><span>'+left+'</span><span>'+right+'</span></div></div><div class="earn-gain"><strong>'+(gain?_eFmtTL(gain):'—')+'</strong><small>'+gainText+'</small></div></div></div>';
  var insights=_eInsights(inv);
  return kpis+'<div class="earn-grid2">'+barem+insights+'</div>'+_eAnalytics(d,inv,bpp,ypp);
}
function _eInsights(inv){var html='<div class="earn-card earn-section"><div class="earn-head"><div><div class="earn-title">Yönetici İçgörüsü</div><div class="earn-sub">Bugün aksiyon alınabilecek alanlar</div></div></div><div class="earn-insights">';if(!inv){html+='<div class="earn-insight"><div class="earn-ico">🏆</div><div><b>Asis kritik YPP bareminde</b><p>14.000 puana yalnızca 79 puan kaldı.</p></div><span class="earn-badge green">+₺70B</span></div><div class="earn-insight"><div class="earn-ico">🎯</div><div><b>Kılavuzlar BPP fırsatı</b><p>%90 HGO baremine geçiş yaklaşık +₺31B etki yaratır.</p></div><span class="earn-badge blue">Yakın</span></div><div class="earn-insight"><div class="earn-ico">🛡</div><div><b>DSL Spin kontrolü</b><p>Eylül kuralında %10 üzeri kısım hedef ve YPP puanından düşer.</p></div><span class="earn-badge green">%10 limit</span></div>'}else{var next=_eNextYppBarem(inv.points),rem=next.points-inv.points,bppPot=_eBppPotential(inv),yppPot=_eSharePotential(inv);html+='<div class="earn-insight"><div class="earn-ico">⭐</div><div><b>'+inv.name+' · '+_eFmt(inv.points)+' puan</b><p>'+_eFmt(next.points)+' baremine '+_eFmt(rem)+' puan kaldı.</p></div><span class="earn-badge '+(inv.yppRate?'green':'red')+'">'+(inv.yppRate?'YPP aktif':'HGO düşük')+'</span></div><div class="earn-insight"><div class="earn-ico">◎</div><div><b>Ağırlıklı HGO %'+_eFmt(inv.hgo,2)+'</b><p>BPP paylaşımı %'+inv.bppRate+' · YPP paylaşımı %'+inv.yppRate+'</p></div><span class="earn-badge blue">HGO</span></div><div class="earn-insight"><div class="earn-ico">₺</div><div><b>Fırsat etkisi</b><p>YPP '+(yppPot?_eFmtTL(yppPot):'—')+' · BPP '+(bppPot?_eFmtTL(bppPot):'—')+'</p></div><span class="earn-badge amber">'+dAsOf()+'</span></div>'}return html+'</div></div>'}
function dAsOf(){var d=_eData();return d?d.asOf.replace(' Eylül 2026',' Eyl'):'26 Eyl'}
function _eAnalytics(d,inv,bpp,ypp){var cats=inv?inv.hgoCats:d.portfolio.hgoCats,names=[['Mobil','mobil',35],['DSL','dsl',35],['IPTV','iptv',10],['DTH','dth',5],['Akıllı Cihaz','smart',10],['Diğer Cihaz','other',5]];var rows=names.map(function(x){var v=cats[x[1]],st=_eCatStatus(v);return '<tr><td>'+x[0]+'<div class="earn-mini-bar"><i style="width:'+Math.min(100,v/1.3)+'%"></i></div></td><td class="earn-hgo '+st[1]+'">%'+_eFmt(v,1)+'</td><td>%'+x[2]+'</td><td>'+st[0]+'</td></tr>'}).join('');var total=bpp+ypp,bp=total?(bpp/total*100):0;var rules=d.pointRules.slice(0,8).map(function(r){return '<div class="earn-rule"><span>'+r[0]+'</span><strong>+'+r[1]+'p</strong></div>'}).join('');return '<div class="earn-grid3"><div class="earn-card earn-section"><div class="earn-head"><div><div class="earn-title">BPP / HGO Performansı</div><div class="earn-sub">Kategori katkıları · %70 altı katkı yok, %130 tavan</div></div></div><table class="earn-hgo-table"><thead><tr><th>Kategori</th><th>HGO</th><th>Ağırlık</th><th>Durum</th></tr></thead><tbody>'+rows+'</tbody></table></div><div class="earn-card earn-section"><div class="earn-head"><div><div class="earn-title">Kazanç Dağılımı</div><div class="earn-sub">BPP + YPP mevcut hesap</div></div></div><div class="earn-donut-wrap"><div class="earn-donut" style="background:conic-gradient(var(--e-cyan) 0 '+bp.toFixed(1)+'%,var(--e-purple) '+bp.toFixed(1)+'% 100%)"><div class="earn-donut-center">'+_eFmtTL(total).replace(',00','')+'<span>Toplam</span></div></div><div class="earn-legend"><div><span>BPP</span><b>'+_eFmtTL(bpp)+'</b></div><div><span>YPP</span><b>'+_eFmtTL(ypp)+'</b></div><div><span>Gelir paylaşımı</span><b style="color:#ffd085">Veri bekleniyor</b></div></div></div></div><div class="earn-card earn-section"><div class="earn-head"><div><div class="earn-title">Eylül Puan Motoru</div><div class="earn-sub">Yüksek etkili işlem puanları</div></div><span class="earn-pill">RULESET 09/26</span></div><div class="earn-rule-list">'+rules+'</div><div class="earn-note">Faturalı Taahhütlü Yeni Nesil aktivasyon, aynı ay taahhüt koşulunu sağlarsa 12 puan; Bayiden Teslimat işlemleri hedefe girebilir ancak YPP puanına dahil edilmez.</div></div></div>'}
function _eTabs(){var tabs=[['overview','Yatırımcılar'],['ypp','YPP Detay'],['bpp','BPP Detay'],['data','Veri Merkezi']];return '<div class="earn-tabs">'+tabs.map(function(t){return '<button class="earn-tab '+(earningsState.tab===t[0]?'active':'')+'" onclick="earningsTab(\''+t[0]+'\')">'+t[1]+'</button>'}).join('')+'</div>'+_ePanel()}
function _ePanel(){var d=_eData();if(earningsState.tab==='ypp')return _eYppPanel(d);if(earningsState.tab==='bpp')return _eBppPanel(d);if(earningsState.tab==='data')return _eDataPanel(d);return _eInvestorPanel(d)}
function _eInvestorPanel(d){var rows=d.investors.map(function(x){return '<tr><td><b>'+x.name+'</b><div style="font-size:7.5px;color:#6f929f">'+x.id+'</div></td><td>%'+_eFmt(x.hgo,2)+'</td><td>'+_eFmt(x.points)+'</td><td class="earn-money">'+_eFmtTL(x.bpp)+'</td><td class="earn-money">'+_eFmtTL(x.ypp)+'</td><td class="earn-money">'+_eFmtTL(x.bpp+x.ypp)+'</td><td><span class="earn-badge '+(x.hgo>=80?'green':'red')+'">'+(x.hgo>=80?'Prim aktif':'HGO eşiği')+'</span></td></tr>'}).join('');return '<div class="earn-card earn-table-card earn-panel active"><div class="earn-table-toolbar"><b>Yatırımcı Bazlı Prim Görünümü</b><span>26 Eylül itibarıyla</span></div><div style="overflow:auto"><table class="earn-data-table"><thead><tr><th>Yatırımcı</th><th>HGO</th><th>YPP Puan</th><th>BPP</th><th>YPP</th><th>Toplam</th><th>Durum</th></tr></thead><tbody>'+rows+'</tbody></table></div></div>'}
function _eYppPanel(d){var rows=d.investors.map(function(x){var cur=_eCurrentYppBarem(x.points),next=_eNextYppBarem(x.points);return '<tr><td><b>'+x.name+'</b></td><td>'+_eFmt(x.points)+'</td><td>%'+x.yppRate+'</td><td>'+(cur?_eFmt(cur.points):'—')+'</td><td>'+_eFmt(next.points)+'</td><td>'+_eFmt(Math.max(0,next.points-x.points))+'</td><td class="earn-money">'+_eFmtTL(x.ypp)+'</td><td class="earn-pos">'+(_eSharePotential(x)?('+'+_eFmtTL(_eSharePotential(x))):'—')+'</td></tr>'}).join('');return '<div class="earn-card earn-table-card earn-panel active"><div class="earn-table-toolbar"><b>YPP Barem ve Kazanç Takibi</b><span>Eylül 2026 puan tablosu</span></div><div style="overflow:auto"><table class="earn-data-table"><thead><tr><th>Yatırımcı</th><th>Puan</th><th>Paylaşım</th><th>Mevcut Barem</th><th>Sonraki</th><th>Kalan</th><th>YPP</th><th>Ek Potansiyel</th></tr></thead><tbody>'+rows+'</tbody></table></div></div>'}
function _eBppPanel(d){var rows=d.investors.map(function(x){var n=_eNextBpp(x.hgo),pot=_eBppPotential(x);return '<tr><td><b>'+x.name+'</b></td><td>%'+_eFmt(x.hgo,2)+'</td><td>%'+x.bppRate+'</td><td>'+_eFmtTL(x.base)+'</td><td class="earn-money">'+_eFmtTL(x.bpp)+'</td><td>'+(n?('%'+_eFmt(n.min,0)):'—')+'</td><td class="'+(pot?'earn-pos':'earn-zero')+'">'+(pot?('+'+_eFmtTL(pot)):'—')+'</td></tr>'}).join('');var inv=_eInvestor(),branches='';if(inv){branches='<div class="earn-card earn-section" style="margin-top:10px"><div class="earn-head"><div><div class="earn-title">'+inv.name+' · Şube Baz Tutarları</div><div class="earn-sub">HGO yatırımcı bazında, baz tutar şube bazında</div></div></div><div class="earn-branch-list">'+inv.branches.map(function(b){return '<div class="earn-branch"><code>'+b.code+'</code><span>'+b.name+'</span><strong>'+_eFmtTL(b.base)+'</strong><span class="earn-source-tag '+(b.source==='Manuel'?'manual':'')+'">'+b.source+(b.protected?' · Koruma':'')+'</span></div>'}).join('')+'</div></div>'}return '<div class="earn-card earn-table-card earn-panel active"><div class="earn-table-toolbar"><b>BPP HGO / Baz Tutar Takibi</b><span>Koruma senaryosu üstteki düğmeden açılır</span></div><div style="overflow:auto"><table class="earn-data-table"><thead><tr><th>Yatırımcı</th><th>HGO</th><th>BPP %</th><th>Baz Tutar</th><th>BPP</th><th>Sonraki HGO</th><th>Ek Potansiyel</th></tr></thead><tbody>'+rows+'</tbody></table></div></div>'+branches}
function _eDataPanel(d){return '<div class="earn-source-grid">'+d.sources.map(function(s){var ok=s.status==='Hazır';return '<div class="earn-card earn-source"><b>'+s.name+'</b><p>'+s.detail+'</p><div class="'+(ok?'ok':'wait')+'">'+(ok?'✓ ':'• ')+s.status+'</div></div>'}).join('')+'</div><div class="earn-note">Bu sürüm 26 Eylül snapshot verisini kullanır. Sonraki geliştirme adımında Mobil / DSL / TV / Cihaz / Hedef Excel yüklemeleri doğrudan bu Veri Merkezi üzerinden güncellenebilir hale getirilecektir.</div>'}
function renderEarningsPage(){var root=document.getElementById('earnings-app'),d=_eData();if(!root)return;if(!d){root.innerHTML='<div class="earn-card earn-section">Prim verisi yüklenemedi.</div>';return}var opts='<option value="all">Tüm Yatırımcılar</option>'+d.investors.map(function(x){return '<option value="'+x.id+'" '+(earningsState.investor===x.id?'selected':'')+'>'+x.name+' · '+x.id+'</option>'}).join('');root.innerHTML='<div class="earn-hero"><div><div class="earn-eyebrow">Yusuf Dilki · TTM</div><h1>Prim & Kazanç Dashboard</h1><p>BPP · YPP · HGO · barem · fırsat takibi</p></div><div class="earn-status">● '+d.ruleset+' aktif</div></div><div class="earn-toolbar"><label><span>Dönem</span><select disabled><option>'+d.periodLabel+'</option></select></label><label><span>Yatırımcı</span><select onchange="earningsSelectInvestor(this.value)">'+opts+'</select></label><button class="earn-toggle '+(earningsState.protection?'on':'')+'" onclick="earningsToggleProtection()">Koruma: '+(earningsState.protection?'Açık':'Kapalı')+'</button><div class="spacer"></div><div class="earn-date">Son veri · '+d.asOf+'</div></div>'+_eOverview(d,_eInvestor())+_eTabs()}
