/* Run with: node tools/month-end-report.test.js */
const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const path = require('node:path');
const root = path.join(__dirname, '..');
const storage = {};
const ctx = vm.createContext({console:{log(){},warn(){}},localStorage:{getItem:k=>storage[k],setItem:(k,v)=>{storage[k]=v;}},TextEncoder,Uint8Array,atob,Set,Date,document:{},XLSX:{utils:{sheet_to_json:s=>s}}});
vm.runInContext(fs.readFileSync(path.join(root,'js/data.js'),'utf8'),ctx);
vm.runInContext(fs.readFileSync(path.join(root,'js/history-loader.js'),'utf8'),ctx);
vm.runInContext(fs.readFileSync(path.join(root,'js/parser.js'),'utf8').replace(/^wire\("drop.*$/gm,''),ctx);
vm.runInContext(fs.readFileSync(path.join(root,'js/month-end-report.js'),'utf8'),ctx);
function run(code){return vm.runInContext(code,ctx);}
ctx.commitmentHeaders=[['Mobil Taahhüt Upsell','DSL Taahhüt','Mobil Taahhüt','DSL Taahhüt','Mobil Taahhüt'],['Aktivasyon','Hedef','Hedef','Aktivasyon','Aktivasyon']];
assert.equal(run('commitmentColumns(commitmentHeaders,1).dsl'),3,'Match activation under the exact product heading');
assert.equal(run('commitmentColumns(commitmentHeaders,1).mobil'),4,'Mobil upsell is a separate metric');
assert.equal(run('commitmentColumns(commitmentHeaders,1).mobilUpsell'),0);
ctx.commitmentRow=[12,0,0,'-',null];
assert.equal(run('readCommitments(commitmentRow,commitmentColumns(commitmentHeaders,1)).dsl'),0);
assert.equal(run('readCommitments(commitmentRow,commitmentColumns(commitmentHeaders,1)).mobil'),null);
assert.equal(run("merCommitmentTotal([{commitments:{dsl:5}},{commitments:{dsl:null}}],'dsl')"),null,'Missing commitments must not become zero');
function dealer(code,h,a,parent='900'){return {kod:code,fullName:'Şirket '+code,anaBayiKod:parent,sy:'Yusuf Dilki',prods:Object.fromEntries(run('MER_PRODUCTS').map(p=>[p.key,{h,a}]))};}
ctx.A=dealer('1',100,100);ctx.B=dealer('2',900,450);
assert.ok(Math.abs(run("merAggregate([A,B],'DSL').g")-55)<1e-9,'HGO must be weighted by target');
ctx.B.prods.DSL.a=null;
assert.equal(run("merAggregate([A,B],'DSL').a"),null,'Missing actual is not zero');
ctx.B.prods.DSL.a=450;ctx.B.prods.DSL.h=null;
assert.equal(run("merAggregate([A,B],'DSL').g"),null,'Missing target cannot produce HGO');
ctx.B.prods.DSL.h=900;
ctx.source={period:'2026-03',ttm:{bayiler:{'1':ctx.A,'2':ctx.B},pers:{}},edm:null,closed:true};
assert.equal(run('merGroups(source).length'),1,'Group by main account code, regardless of branch names');
assert.equal(run('merGroups(source)[0].rows.length'),2);
run("MER_PARENTS['2']='901'");assert.equal(run('merGroups(source).length'),2);run('MER_PARENTS={}');
ctx.A.anaBayiKod='';ctx.B.anaBayiKod='';ctx.A.fullName='A şirket';ctx.B.fullName='B şirket';
assert.equal(run('merGroups(source).length'),2,'Similar short names must not silently merge legal entities');
ctx.A.anaBayiKod='900';ctx.B.anaBayiKod='900';
ctx.hist={};for(const year of [2025,2026])for(const month of [1,2,3]){if(year===2025&&month===2)continue;const period=year+'-'+String(month).padStart(2,'0');ctx.hist[period]={period,channel:'TTM',dealers:[{bayiKodu:'1',bayiAdi:'A',dsl:{hedef:100,adet:year===2025?40:60}},{bayiKodu:'2',bayiAdi:'B',dsl:{hedef:900,adet:year===2025?160:240}}]};}
ctx.HIST2_DATA=ctx.hist;run("MER_LIVE=null;MER_ARCHIVES={};C=merContext(source,'account','code:900');P=MER_PRODUCTS.find(p=>p.key==='DSL');S=merStats(C,P)");
assert.equal(run('S.months'),3);assert.equal(run('S.pairMonths'),2,'Only same months in both years participate');
assert.equal(run('S.pairB'),400);assert.equal(run('S.pairA'),850);assert.equal(run('S.ytdYoY'),112.5);
assert.equal(run('S.prevYearA'),200,'YoY keeps the same-month prior-year actual for the split comparison card');
assert.equal(run('S.prevA'),300,'MoM keeps the immediately previous month actual');
assert.equal(run("merHistoricalValue(C,'2026-02',P).a"),300,'Embedded sample must not override historical closure');
ctx.HIST2_DATA['2026-02'].dealers.pop();assert.equal(run("merHistoricalValue(C,'2026-02',P).a"),60,'Cari month uses branches actually reported that month');
assert.equal(run("merHistoricalValue(C,'2026-02',P).rowCount"),1,'Cari reports month-specific coverage');
run("BC=merContext(source,'branch','2')");assert.equal(run("merHistoricalValue(BC,'2026-02',P)"),null,'Missing individual branch is not zero');
ctx.source.edm={bayiler:{'3':dealer('3',500,250)},pers:{}};
run("R=merContext(source,'region','')");assert.equal(run("merAggregate(R.rows,'DSL').g"),800/1500*100);
assert.equal(run("merHistoricalValue(R,'2026-01',P)"),null,'Combined region cannot use TTM-only history');
// Workbook fixtures: exact metadata, two EDM parents, another region and rollups.
const heads=['Ana Bölge','Bölge','Bayi Kodu','Bayi Adı','Ana Bayi Kodu','İl','Satış Yöneticisi'];
for(const p of ['Postpaid','Prepaid','Toplam Mobil','DSL','IPTV','Uydu','Akıllı Cihaz','Diğer Cihaz'])heads.push(p+' Hedef',p+' Gerçekleşen');
const edmRow=(code,parent,region='KUZEY ANADOLU')=>['ANADOLU',region,code,'EDM '+code,parent,'SAMSUN','Yusuf Dilki',...Array(8).fill([100,70]).flat()];
ctx.wb={SheetNames:['EDM BUAY'],Sheets:{'EDM BUAY':[heads,edmRow('10','507868'),edmRow('11','507999'),edmRow('12','507868','BATI ANADOLU'),edmRow('','507868')]}};
assert.equal(run("Object.keys(parseEDMSheet(wb,{region:true}).detay.bayiler).length"),2,'Region includes all parents, excludes other region and rollup');
assert.equal(run("Object.keys(parseEDMSheet(wb,{group:true}).detay.bayiler).length"),3,'Group includes all Anadolu regions and excludes non-numeric rollups');
assert.equal(run("parseEDMSheet(wb,{region:true}).detay.bayiler['11'].prods.IPTV.a"),70);
assert.equal(run("parseEDMSheet(wb,{region:true}).detay.bayiler['11'].anaBayiKod"),'507999');
assert.equal(run("Object.keys(parseEDMSheet(wb).detay.bayiler).includes('11')"),false,'Existing EDM screen keeps its parent filter');
assert.equal(run("Object.keys(parseEDMSheet(wb,{group:true}).detay.bayiler).length"),3,'Group scope includes every Anadolu EDM row regardless of regional parent');
const noUydu=heads.slice(0,heads.indexOf('Uydu Hedef')).concat(heads.slice(heads.indexOf('Uydu Gerçekleşen')+1));
ctx.noUydu={SheetNames:['EDM BUAY'],Sheets:{'EDM BUAY':[noUydu,edmRow('10','507868').slice(0,heads.indexOf('Uydu Hedef')).concat(edmRow('10','507868').slice(heads.indexOf('Uydu Gerçekleşen')+1))]}};
assert.equal(run("parseEDMSheet(noUydu,{region:true}).detay.bayiler['10'].prods.Uydu"),undefined,'Do not fabricate absent IPTV/TV split');
const dashRow=edmRow('13','507868');
for(const name of ['Prepaid','DSL','IPTV','Uydu','Akıllı Cihaz','Diğer Cihaz'])for(const suffix of [' Hedef',' Gerçekleşen'])dashRow[heads.indexOf(name+suffix)]='-';
ctx.dashWB={SheetNames:['EDM BUAY'],Sheets:{'EDM BUAY':[heads,edmRow('10','507868'),dashRow]}};
assert.equal(run("merAggregate(Object.values(parseEDMSheet(dashWB,{region:true}).detay.bayiler),'DSL').a"),70,'Explicit no-activity dash must not blank the regional total');
dashRow[heads.indexOf('DSL Gerçekleşen')]='';
assert.equal(run("merAggregate(Object.values(parseEDMSheet(dashWB,{region:true}).detay.bayiler),'DSL').a"),null,'A genuinely blank product cell remains unknown');
const ttmHeader=Array(90).fill('');ttmHeader[0]='Ana Bölge';
const ttm=Array(90).fill(0);Object.assign(ttm,{0:'ANADOLU',1:'KUZEY ANADOLU',2:'22',3:'Uzun Şirket Tam Ticari Unvan',4:'4100170',5:'SAMSUN',7:'Yusuf Dilki'});for(const i of [49,53,57,69,73,77,81]){ttm[i]=100;ttm[i+1]=80;}
const emp=Array(70).fill(0);Object.assign(emp,{0:'ANADOLU',1:'KUZEY ANADOLU',2:'22',3:ttm[3],4:'Yusuf Dilki',5:'SAMSUN',6:'Personel',7:'202609'});
ctx.ttmWB={SheetNames:['ÇALIŞAN','TTM BUAY'],Sheets:{'ÇALIŞAN':[['Ana Bölge'],emp],'TTM BUAY':[ttmHeader,ttm]}};
assert.equal(run("parseWB(ttmWB).detay.bayiler['22'].anaBayiKod"),'4100170');
assert.equal(run("parseWB(ttmWB).detay.bayiler['22'].fullName"),'Uzun Şirket Tam Ticari Unvan');
assert.equal(run("Object.keys(parseWB(ttmWB).detay.grupBayiler).length"),1,'TTM parser exposes Anadolu group rows separately from Kuzey Anadolu rows');
ctx.parsed=run('parseWB(ttmWB)');ctx.parsed.syData={calismaGun:30,calisilanGun:10};run('merCaptureUpload(parsed,null)');assert.equal(run('MER_LIVE.closed'),false);assert.equal(run('MER_LIVE.sample'),false);
ctx.parsed.syData.calisilanGun=30;run('merCaptureUpload(parsed,null)');assert.equal(run('MER_LIVE.closed'),true);assert.ok(storage.tt_month_end_archives_v1);
ctx.fakeCanvas={width:4096,height:3072,toDataURL:()=> 'data:image/jpeg;base64,/9j/2Q=='};
const bytes=run('merCanvasToPdfBytes([fakeCanvas,fakeCanvas])');const pdf=Buffer.from(bytes).toString('latin1');assert.ok(pdf.includes('/Count 2'));assert.ok(pdf.includes('xref\n0 9'));for(const offset of pdf.matchAll(/(\d{10}) 00000 n/g))assert.ok(/^\d+ 0 obj/.test(pdf.slice(+offset[1])),'PDF xref points to object');
// Clean comparison matrix: one product row, three comparison columns.
ctx.ytdFixture={products:['mobil','dsl','iptv','uydu','akilliCihaz','digerCihaz'].map((hist,i)=>({hist,key:['Toplam Mobil','DSL','IPTV','Uydu','Akıllı Cihaz','Diğer Cihaz'][i],label:hist,s:{pairB:[6636,569,208,111,733,720][i],pairA:[7010,610,256,90,779,930][i],ytdA:[7010,610,256,90,779,930][i],a:[900,80,40,12,95,110][i],prevYearA:[800,100,32,15,90,100][i],prevA:[850,100,35,13,92,115][i],pairMonths:8}})),source:{period:'2026-09'}};
const yearCard=run('merYtdChart(ytdFixture)');
assert.equal((yearCard.match(/class="mer-compare-row"/g)||[]).length,6,'Each product appears once');
assert.equal((yearCard.match(/class="mer-compare-cell/g)||[]).length,18,'Each product has YTD, YoY and MoM cells');
assert.ok(yearCard.includes('>YTD<'));
assert.ok(yearCard.includes('>YoY<'));
assert.ok(yearCard.includes('>MoM<'));
const growthCell=run("merCompareCell(125,100,'test')");
assert.ok(growthCell.includes('+25.0%')||growthCell.includes('+25,0%'),'Comparison cell shows growth rate');
assert.ok(growthCell.includes('+25 adet'),'Comparison cell shows signed unit difference');
const lossCell=run("merCompareCell(80,100,'test')");
assert.ok(lossCell.includes('-20.0%')||lossCell.includes('-20,0%'));
assert.ok(lossCell.includes('-20 adet'));
const missingCell=run("merCompareCell(80,null,'test')");
assert.ok(missingCell.includes('—'),'Missing comparison remains unknown');

// A full ring caps its fill at 100%, while retaining the real HGO label.
assert.ok(run("merHgoRing(112,'#00b6a6','test')").includes('stroke-dashoffset="0"'));
assert.ok(run("merHgoRing(112,'#00b6a6','test')").includes('>%112</text>'));
assert.ok(run("merHgoRing(null,'#00b6a6','missing')").includes('>—</text>'));
ctx.cardFixture={products:[{key:'DSL',hist:'dsl',s:{g:112,a:112,h:100,gap:12}},{key:'IPTV',hist:'iptv',s:{g:80,a:64,h:80,gap:-16}},{key:'Uydu',hist:'uydu',s:{g:null,a:null,h:null,gap:null}}]};
const cards=run('merSignals(cardFixture)');assert.ok(cards.includes('HEDEF ÜSTÜ'));assert.ok(cards.includes('+12 <small>adet</small>'));assert.ok(cards.includes('KALAN'));assert.ok(cards.includes('16 <small>adet</small>'));assert.ok(cards.includes('VERİ YOK'));
// Real archives: Primetech opened a new branch; Asis has month-specific coverage.
ctx.HIST2_DATA=Object.fromEntries(fs.readdirSync(path.join(root,'data/history')).filter(f=>/^20.*\.json$/.test(f)).map(f=>[f.slice(0,7),JSON.parse(fs.readFileSync(path.join(root,'data/history',f),'utf8'))]));
ctx.edmPack=JSON.parse(fs.readFileSync(path.join(root,'data/history/edm-summary.json'),'utf8'));
ctx.edmSummary=run('hist2ExpandEdmSummary(edmPack)');
for(const [period,edm] of Object.entries(ctx.edmSummary))if(ctx.HIST2_DATA[period]&&!ctx.HIST2_DATA[period].monthEnd)ctx.HIST2_DATA[period].edm=edm;
run("MER_LIVE=null;MER_ARCHIVES={};MER_PARENTS={};HS=merFromHistory(HIST2_DATA['2026-08']);PG=merGroups(HS).find(g=>g.name.includes('PRİMETECH'));PC=merContext(HS,'account',PG.id);AG=merGroups(HS).find(g=>g.name.includes('ASİS'));AC=merContext(HS,'account',AG.id)");
assert.equal(run("merStats(PC,MER_TRENDS[0]).months"),8,'New branch must not blank prior cari months');
assert.equal(run("merStats(AC,MER_TRENDS[0]).months"),8,'All available Asis monthly totals are plotted');
assert.equal(run("merHistoricalValue(AC,'2026-06',MER_TRENDS[0]).rowCount"),3);
assert.equal(run("merHistoricalValue(AC,'2026-06',MER_TRENDS[0]).a"),1373);
assert.equal(run("merHistoricalValue(AC,'2026-06',MER_TRENDS[0]).h"),1564);
const tvStats=run("merStats(AC,{key:'Toplam TV',hist:'tv'})");assert.equal(tvStats.months,8);
const tvExpected=run("merStats(AC,MER_PRODUCTS.find(p=>p.hist==='iptv')).ytdA+merStats(AC,MER_PRODUCTS.find(p=>p.hist==='uydu')).ytdA");assert.equal(tvStats.ytdA,tvExpected,'TV combines IPTV and Uydu for the same months');
ctx.tvIncomplete={prods:{IPTV:{h:10,a:8}}};assert.equal(run("merAggregate([tvIncomplete],'Toplam TV').g"),null,'Missing TV split cannot become zero');
const ytdPanel=run('merYtdPerformance(AC)');assert.equal((ytdPanel.match(/<article/g)||[]).length,4);assert.ok(!ytdPanel.includes('Diğer'));assert.ok(ytdPanel.includes('HGO'));assert.ok(ytdPanel.includes('adet ·'));
// Explicit parent changes take precedence over current branch membership.
ctx.transfer={period:'2026-01',ttm:{bayiler:{'1':dealer('1',100,90,'999')},pers:{}}};
run("TC=merContext(source,'account','code:900')");assert.equal(run('merAccountMonthRows(TC,transfer).length'),0);
run("MER_PARENTS['1']='900'");assert.equal(run('merAccountMonthRows(TC,transfer).length'),1);run('MER_PARENTS={}');
// Cari includes national sibling branches; regional screens keep their boundary.
const foreign=Object.assign([],ttm,{1:'ORTA ANADOLU',2:'23',5:'ANKARA'});
const unrelated=Object.assign([],ttm,{1:'BATI ANADOLU',2:'24',4:'888'});
ctx.ttmWB.Sheets['TTM BUAY'].push(foreign,unrelated);
ctx.national=run('parseWB(ttmWB)');
assert.equal(Object.keys(ctx.national.detay.bayiler).length,1);
assert.equal(Object.keys(ctx.national.detay.grupBayiler).length,3,'Group rows retain every Anadolu TTM region');
assert.equal(Object.keys(ctx.national.detay.cariBayiler).length,2,'Only national siblings of regional caris are kept');
ctx.national.syData={calismaGun:30,calisilanGun:30};run('merCaptureUpload(national,null)');
assert.equal(run('merGroups(MER_LIVE)[0].rows.length'),2);
assert.equal(run("merContext(MER_LIVE,'region','').rows.length"),1);
assert.equal(run("merAggregate(merContext(MER_LIVE,'account','code:4100170').rows,'DSL').a"),160);
run('MER_LIVE=null;MER_ARCHIVES={};OS=merFromHistory(HIST2_DATA["2026-08"]);OC=merContext(OS,"account","code:7000514")');
assert.deepEqual(Array.from(run('OC.rows.map(d=>d.kod).sort()')),['4057503','4100756','4100760','7000514']);
assert.equal(run("merContext(OS,'region','').rows.length"),267,'August region includes 23 TTM and 244 EDM branches');
assert.equal(run('merStats(OC,MER_TRENDS[0]).ytdA'),10403);
assert.equal(run('merHistoricalValue(OC,"2025-04",MER_TRENDS[0]).rowCount'),2,'Later openings are not fabricated in older months');
assert.equal(run('merHistoricalValue(OC,"2025-05",MER_TRENDS[0]).rowCount'),3);
assert.equal(run('merHistoricalValue(OC,"2025-07",MER_TRENDS[0]).rowCount'),4);
ctx.legacy=JSON.parse(JSON.stringify(run('OS')));delete ctx.legacy.ttm.cariBayiler;
assert.equal(run('merGroups(legacy).find(g=>g.code==="7000514").rows.length'),4,'Closed legacy archive recovers matching-month external rows');
ctx.partial=JSON.parse(JSON.stringify(ctx.legacy));ctx.partial.closed=false;ctx.partial.sample=false;
assert.equal(run('merGroups(partial).find(g=>g.code==="7000514").rows.length'),2,'Closing history must not be mixed with an intra-month upload');
// Published September closing retains staff, EDM and all account branches.
run('MER_LIVE=null;MER_ARCHIVES={};SEP=merSource("2026-09")');
assert.equal(run('SEP.closed'),true);
assert.equal(run('Object.keys(SEP.ttm.bayiler).length'),23);
assert.equal(run('Object.values(SEP.ttm.pers).reduce((n,p)=>n+p.length,0)'),122);
assert.equal(run('Object.keys(SEP.edm.bayiler).length'),243);
assert.equal(run('merContext(SEP,"account","code:7000514").rows.length'),4);
assert.equal(run('SEP.ttm.bayiler["4052718"].prods["Toplam Mobil"].a'),440);
assert.equal(run('SEP.ttm.pers["4052718"].reduce((n,p)=>n+p.prods["Toplam Mobil"].a,0)'),440);
run("GCTX=merContext(SEP,'group','')");
assert.equal(run("merAggregate(GCTX.rows,'Postpaid').h"),27180,'Anadolu GM Faturalı target comes from verified closing workbook');
assert.equal(run("merAggregate(GCTX.rows,'Postpaid').a"),30022,'Anadolu GM Faturalı actual comes from verified closing workbook');
assert.equal(run("merAggregate(GCTX.rows,'Prepaid').h"),25113,'Anadolu GM Faturasız target comes from verified closing workbook');
assert.equal(run("merAggregate(GCTX.rows,'Prepaid').a"),24455,'Anadolu GM Faturasız actual comes from verified closing workbook');
run("GDETAIL=merDetailRows(GCTX)");
assert.equal(run('GDETAIL.length'),4,'Group detail contains Anadolu GM plus three regional directorates');
assert.equal(run("GDETAIL[0].name"),'ANADOLU GM');
assert.ok(run("GDETAIL.some(r=>r.name==='BATI ANADOLU'&&r.sub.includes('BAYRAM ÖZÖNER'))"));
assert.ok(run("GDETAIL.some(r=>r.name==='KUZEY ANADOLU'&&r.sub.includes('SADI UR'))"));
assert.ok(run("GDETAIL.some(r=>r.name==='ORTA ANADOLU'&&r.sub.includes('İLKER KOPKOP'))"));
assert.equal(run('merContext(SEP,"region","").rows.length'),266);
run('RC=merContext(SEP,"region","")');
ctx.HIST2_CHANNEL_SUMMARY=JSON.parse(fs.readFileSync(path.join(root,'data/history/channel-activation-summary.json'),'utf8'));
ctx.HIST2_REGION_BENCHMARKS=JSON.parse(fs.readFileSync(path.join(root,'data/history/region-benchmarks.json'),'utf8'));
run('CAM=merRegionChannelAverages(RC)');
assert.equal(run('CAM.monthCount'),9,'Regional channel averages use January-September YTD');
assert.equal(Math.round(run('CAM.rows.mobil.current[0]*10'))/10,325.9,'September TTM Mobil is shown per sales point');
assert.equal(Math.round(run('CAM.rows.mobil.current[1]*10'))/10,58.6,'September TTBN Mobil is shown per sales point');
assert.equal(Math.round(run('CAM.rows.mobil.current[2]*10'))/10,8.8,'September ESN Mobil is shown per sales point');
assert.equal(Math.round(run('CAM.rows.mobil.ytd[0]*10'))/10,350.3,'TTM Mobil YTD is weighted by sales-point months');
assert.equal(Math.round(run('CAM.rows.mobil.ytd[1]*10'))/10,66.9,'TTBN Mobil YTD is weighted by sales-point months');
assert.equal(Math.round(run('CAM.rows.mobil.ytd[2]*10'))/10,11.9,'ESN Mobil YTD is weighted by sales-point months');
assert.deepEqual(Array.from(run('CAM.rows.mobil.currentPoints')),[23,121,121],'September channel point counts are retained');
assert.equal(Math.round(run('CAM.rows.mobil.gmYtd[0]*10'))/10,302.5,'Anadolu GM TTM Mobil YTD point average is loaded');
assert.equal(Math.round(run('CAM.rows.mobil.gmYtd[1]*10'))/10,63.9,'Anadolu GM TTBN Mobil YTD point average is loaded');
assert.equal(Math.round(run('CAM.rows.mobil.gmCurrent[0]*10'))/10,301.1,'Anadolu GM September TTM Mobil point average is loaded');
const regionSummary=run('merSummary(RC)');
assert.ok(regionSummary.includes('NOKTA BAŞI ORTALAMA AKTİVASYON'),'Region replaces sales-manager card with point-efficiency matrix');
assert.ok(regionSummary.includes('adet / nokta'),'Regional matrix explains the per-point unit');
const gmCell=run("merChannelValue(350.3,302.5,'ttm')");
assert.ok(gmCell.includes('350,3')&&gmCell.includes('302,5'),'Point-average cell shows Kuzey Anadolu / Anadolu GM averages together');
assert.ok(gmCell.includes('(+15,8%)'),'GM difference rate is shown below in parentheses');
assert.ok(run("merChannelValue(0,10,'ttm')").includes('>-</small>'),'Zero Kuzey Anadolu value shows dash instead of ratio');
assert.ok(run("merChannelValue(10,0,'ttm')").includes('>-</small>'),'Zero GM value shows dash instead of ratio');
const zeroCell=run("merChannelValue(0,0,'ttm')");
assert.ok(zeroCell.includes('mer-channel-empty')&&zeroCell.includes('>-</b>'),'Both zero values collapse to a single dash');
assert.ok(!zeroCell.includes('0,0')&&!zeroCell.includes('<small'),'Both-zero cell hides values and ratio entirely');
assert.ok(!regionSummary.includes('SATIŞ YÖNETİCİLERİ'),'Region no longer renders the sales-manager table');
assert.equal((regionSummary.match(/class="mer-channel-row"/g)||[]).length,6,'Simplified matrix has six product rows');
assert.equal((regionSummary.match(/class="mer-channel-value /g)||[]).length,36,'Each product has YTD and selected-month TTM TTBN ESN values');
assert.ok(!regionSummary.includes('mer-channel-bars'),'Regional comparison no longer renders mini bar charts');

// Tüm Bölge ay kapanışı artık aynı kapsamlı (TTM + EDM) GM ve Türkiye HGO'larıyla kıyaslanır.
assert.equal(run("merRegionBenchmark(RC,MER_PRODUCTS.find(p=>p.hist==='mobil'),'gm')"),104.2,'September Anadolu GM combined Mobil HGO');
assert.equal(run("merRegionBenchmark(RC,MER_PRODUCTS.find(p=>p.hist==='mobil'),'tr')"),104.6,'September Türkiye combined Mobil HGO');
assert.equal(run("merRegionBenchmark(RC,MER_PRODUCTS.find(p=>p.hist==='dsl'),'gm')"),98.2,'September Anadolu GM combined DSL HGO');
// Grup Müdürlüğü = Anadolu scope. Archived cards use verified Anadolu GM summaries when branch-level group rows are absent.
run('GC=merContext(SEP,"group","")');
assert.equal(run('GC.rows.length'),0,'Legacy closing archive has no raw Anadolu group rows');
assert.equal(run("merStats(GC,MER_PRODUCTS.find(p=>p.hist==='mobil')).a"),54467,'September Anadolu group Mobil activations come from TTM + TTBN + ESN summaries');
assert.equal(run("merStats(GC,MER_PRODUCTS.find(p=>p.hist==='mobil')).g"),104.2,'September Anadolu group Mobil HGO uses the verified GM benchmark');
assert.equal(run("merStats(GC,MER_PRODUCTS.find(p=>p.hist==='dsl')).a"),7304,'September Anadolu group DSL activations are complete');
assert.equal(run("merStats(GC,MER_PRODUCTS.find(p=>p.hist==='mobil')).months"),9,'Group trend has January-September verified coverage');
run("GC.products=MER_PRODUCTS.map(function(p){return Object.assign({},p,{s:merStats(GC,p)});})");
const groupPerformance=run('merPerformanceTable(GC)');
assert.ok(groupPerformance.includes('TR Δ'),'Group closing table compares Anadolu with Türkiye');
assert.ok(!groupPerformance.includes('GM Δ'),'Group closing table does not compare Anadolu with itself');
assert.ok(run('merHeader(GC)').includes('Grup Müdürlüğü'),'Group scope appears in the month-end header');
run("RC.products=MER_PRODUCTS.map(function(p){return Object.assign({},p,{s:merStats(RC,p)});})");
const regionPerformance=run('merPerformanceTable(RC)');
assert.ok(regionPerformance.includes('GM Δ'),'Region closing table has GM comparison');
assert.ok(regionPerformance.includes('TR Δ'),'Region closing table has Türkiye comparison');
assert.ok(!regionPerformance.includes('Aylık Δ'),'Closing table no longer duplicates monthly comparison');
assert.ok(!regionPerformance.includes('Yıllık Δ'),'Closing table no longer duplicates yearly comparison');
assert.ok(!regionPerformance.includes('Bölge Δ'),'Region closing table no longer compares the region with itself');

assert.equal(run("merCommitmentTotal(RC.rows,'dsl')"),333,'Regional DSL commitments equal 112 TTM + 221 EDM');
assert.equal(run("merCommitmentTotal(merRows(SEP,'TTM'),'mobil')"),3512);
assert.equal(run("merCommitmentTotal(merRows(SEP,'EDM'),'mobilUpsell')"),4618);
assert.equal(run("merCommitmentTotal(merContext(SEP,'branch','4052718').rows,'dsl')"),3);
assert.equal(run("merCommitmentTotal(merContext(SEP,'branch','4052718').rows,'mobil')"),190);
const commitmentCards=run('merCommitments(RC)');
assert.ok(commitmentCards.includes('MOBİL TAAHHÜT UPSELL · EDM'),'Regional export identifies the distinct EDM metric');
assert.ok(commitmentCards.includes('IPTV / DSL ORANI · TTM'),'Regional KPI row includes TTM IPTV/DSL ratio');
assert.ok(commitmentCards.includes('%58,2'),'September TTM IPTV/DSL ratio is 701 / 1205 = 58.2%');

// Trend kartları Ocak'tan seçili aya kadar görünür; ürün başlığında tekrar Hedef/Gerçekleşen yazılmaz.
const mobilStats=run("merStats(RC,MER_PRODUCTS.find(p=>p.hist==='mobil'))");
assert.equal(mobilStats.series.length,9,'September trend has January-September data');
ctx.mobilStats=mobilStats;
const spark=run("merSpark(mobilStats,'#087cfa','2026-09',false)");
assert.ok(spark.includes('Oca'),'Trend begins in January');
assert.ok(spark.includes('Eyl'),'Trend reaches selected September');
const trends=run('merTrends(RC)');
assert.ok(!trends.includes('Hedef:'),'Trend product cards do not repeat target text');
assert.ok(!trends.includes('Gerçekleşen:'),'Trend product cards do not repeat actual text');

const septemberTotals={'Toplam Mobil':[16227,15656],DSL:[2364,2268],IPTV:[909,957],Uydu:[179,199],'Akıllı Cihaz':[3034,3209],'Diğer Cihaz':[1865,1906]};
for(const [key,[h,a]] of Object.entries(septemberTotals)){
  ctx.productKey=key;
  assert.equal(run('merAggregate(RC.rows,productKey).h'),h,key+' target matches the closing workbook');
  assert.equal(run('merAggregate(RC.rows,productKey).a'),a,key+' activations match the closing workbook');
  const stats=run('merStats(RC,MER_PRODUCTS.find(p=>p.key===productKey))');
  assert.equal(stats.months,9,'Region has January-September complete TTM + EDM coverage');
  assert.equal(stats.expectedMonths,9);
  assert.equal(stats.pairMonths,9,'January-September now has complete same-month YoY coverage');
  const regionalYtd={'Toplam Mobil':[167296,157692],DSL:[21301,20015],IPTV:[6996,7269],Uydu:[1595,1776],'Akıllı Cihaz':[22771,24179],'Diğer Cihaz':[17316,17695]};
  assert.deepEqual([stats.ytdH,stats.ytdA],regionalYtd[productKey],productKey+' YTD uses all verified 2026 closings');
}
run('MER_ARCHIVES["2026-09"]={period:"2026-09",closed:false,uploadedAt:"2099-01-01T00:00:00Z"}');
assert.equal(run('merSource("2026-09").closed'),true,'An intra-month archive cannot hide the published closing');
run('MER_ARCHIVES["2026-09"]={period:"2026-09",closed:true,uploadedAt:"2000-01-01T00:00:00Z"}');
assert.equal(run('merSource("2026-09").ttm.bayiler["4052718"].prods["Toplam Mobil"].a'),440);
run('MER_ARCHIVES["2026-09"]={period:"2026-09",closed:true,uploadedAt:"2099-01-01T00:00:00Z",revised:true}');
assert.equal(run('merSource("2026-09").revised'),true,'Newer verified uploads remain usable');
run('MER_ARCHIVES={}');
// Grup Müdürlüğü: Anadolu GM verified historical summaries power month closing/trend/YTD.
run("GC=merContext(SEP,'group','');GP=MER_PRODUCTS.find(p=>p.hist==='mobil');GH=merGroupHistoricalValue('2026-09',GP)");
assert.equal(run('GC.name'),'Anadolu Grup Müdürlüğü');
assert.equal(run('GH.a'),54467,'Anadolu GM September Mobil = TTM + TTBN + ESN');
assert.equal(run('GH.g'),104.2,'Anadolu GM HGO uses verified combined GM benchmark');
const groupHeader=run('merHeader(GC)');
assert.ok(groupHeader.includes('Grup Müdürlüğü'),'Month-end header exposes Group Directorate scope');
assert.ok(groupHeader.includes('Anadolu Grup Müdürlüğü'),'Group header keeps the correct group name');
const groupPerformance=run("GC.products=MER_PRODUCTS.map(function(p){return Object.assign({},p,{s:merStats(GC,p)});});merPerformanceTable(GC)");
assert.ok(groupPerformance.includes('TR Δ'),'Group closing compares against Türkiye');
assert.ok(groupPerformance.includes('Faturalı'),'Group month closing explicitly includes Postpaid');
assert.ok(groupPerformance.includes('Faturasız'),'Group month closing explicitly includes Prepaid');
assert.ok(groupPerformance.indexOf('Faturalı')<groupPerformance.indexOf('Faturasız') && groupPerformance.indexOf('Faturasız')<groupPerformance.indexOf('Toplam Mobil'),'Closing product order starts with Postpaid, Prepaid, Total Mobile');
assert.ok(!groupPerformance.includes('GM Δ'),'Group closing does not compare Anadolu GM against itself');
console.log('PASS: weighted totals, missing values, account grouping, aligned YoY, channel coverage, workbook imports, archives, group directorate, multi-page PDF.');
